# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43e0dc8090ef3d0c41f8cee2e59ad650c1c82fd73738d33689311a24e54103483c42bc2f7deda6384389b8159c65d46bf5fa2d3ad35306e0fdb35cdee3fe1b9b

test:
  secret_key_base: ee58aa76c28c9aa2b653995f8c239e55a93f2747539b4ab1b71f6c43dc478e43ac990dddac03492effb49d90de026d1a85c5b96c3a3c662d39d00f425923cb31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
